# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
