# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20161009_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
