# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='source',
            new_name='domain',
        ),
    ]
