# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('articles', '0006_auto_20161010_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleQueue',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='articleview',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
